### ISSUE TITLE
Invalid port info in state DB after configuring split port in config_db.json without changing port_config.ini/platform.json

### ISSUE THREAD

**Issue by Junchao-Mellanox** [Azure/sonic-platform-daemons#110]
**Description**

We found that user can configure split port by directly changing config_db.json without modifying port_config.ini or platform.json. However, the problem is that xcvrd still reads port configuration from port_config.ini/platform.json which would cause wrong information in DB. 

**Steps to reproduce the issue:**
1. User configure split port on Ethernet0 to “1 split 4” in  config_db.json
2. Reboot switch
3. Split port works well, but xcvrd still reads the old port_config.ini and save them to DB.

**Describe the results you received:**

Invalid port information in state DB

**Describe the results you expected:**

State DB have correct port information

**Comment by jleveque** [comment]
I believe the correct fix here is for xcvrd to read port configuration from Config DB, rather than reading from port_config.ini/platform.json files.

**Comment by liat-grozovik** [comment]
@jleveque i agree. none of the files should be edited when the port is breakout via the DPB.
This was probably missed as the xcrv logic is from the time platform.json was not available and breakouts was only via port_config.ini.

**Comment by liorghub** [comment]
@Junchao-Mellanox Please close the bug, fix was merged.

**Comment by liorghub** [comment]
@Junchao-Mellanox please reopen this bug, fix was reverted.

**Comment by liorghub** [comment]
@Junchao-Mellanox 
When you wrote "Invalid port information in state DB" did you refer to TRANSCEIVER_INFO table?

**Comment by liorghub** [comment]
@Junchao-Mellanox I looked at the code and came up with the following conclusion. 
The scenario you described in this bug is not valid.
When user performs split Ethernet0 to 4, he should not delete Ethernet0 from config_db.json, he should just edit the lanes of Ethernet0 and add 3 new ports (Ethernet1, Ethernet2 and Ethernet3)

However, deleting a port from config_db.json can take place when we do split disable.
Split disable is needed in the case where we have more than 128 ports due to split (128 is the maximum since Asic has 128 ports).
If we will split first 16 ports to 8 we will get to total of 128 ports which is the maximum and we will need to disable all other ports.

Split disable scenario for example: 
Split Ethernet0 to 8 will be done by adding Ethernet1, Ethernet2 … Ethernet7 to config_db.json and delete Ethernet8 from config_db.json.
In this case Ethernet8 will still be present in TRANSCEIVER_INFO table since it is the identifier of the second cage.
TRANSCEIVER_INFO table holds data on the physical transceivers which are physically plugged into the switch.
When we deleted Ethernet8 from config_db.json we removed it logically but physically the cage is still there, the transceiver is still plugged and SNMP can still fetch data for this physical cage.
